// <auto-generated />
using EmployeeWebServices.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeWebServices.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    partial class EmployeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("EmployeeWebServices.Models.Employee", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("HourlyWage")
                        .HasColumnType("REAL");

                    b.Property<double>("HoursPerMonth")
                        .HasColumnType("REAL");

                    b.HasKey("Name");

                    b.ToTable("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
